name: Lint and Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint Dockerfiles
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/Dockerfile
        failure-threshold: warning

    - name: Lint Linux Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/Dockerfile.linux
        failure-threshold: warning
        ignore: DL3008

    - name: Validate vcpkg manifest
      run: |
        if ! jq empty docker/vcpkg.json; then
          echo "vcpkg.json is not valid JSON"
          exit 1
        fi
        echo "vcpkg.json is valid"

  lint-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check PowerShell scripts
      uses: microsoft/devskim-action@v1
      with:
        directory-to-scan: docker/

    - name: Validate shell scripts
      run: |
        if [ -f docker/build.sh ]; then
          shellcheck docker/build.sh
        fi